### ISSUE TITLE
Does not load mastodon in-app

### ISSUE THREAD

**Issue by galopeian1** [Vavassor/Tusky#116]
When "Mastodon.social" is typed in I am asked to choose a web browser to load mastodon from, app does not load mastodon.social instance

**Comment by Vavassor** [comment]
Were you able to log in at least? It's part of the OAuth process that it has to go to the site to log in. But I could change it to open the site in a WebView in-app instead of opening it with a browser.

I know at least one browser called Ghostery that would search the URL it's given instead of opening the page. This caused a user who had it as their default browser to not be able to log in.

**Comment by alerque** [comment]
Re using Chrome Tabs instead of WebView to implement this — I don't know what the development end of this looks like but as an end  user I definitely prefer apps that use Chrome Tabs for this.

* The rendering is inevitably better as it tends to stay more up to date than packaged libraries.
* I can use Brave, which includes privacy features that make me much more comfortable.
* I'm more comfortable entering secure data because I can see that HTTPS is implemented correctly as well as for the first two reasons. In app WebViews tend to be missing some of the browser Chrome and frequently miss-implement things like certificate checking.
* It comes with my browser sessions, so there is some chance that I'll already be logged in to a service saving the arduous process of logging it to assorted services from mobile.

**Comment by galopeian1** [comment]
Even when I sign in on firefox it does not authorize me in-app. Do I need to use google chrome to sign in?

**Comment by Vavassor** [comment]
As of Tusky 1.1.3 and commit b6e72a94be90ae7bffddf4ce06ea135130118871 the process uses Custom Tabs for login and falls back to the default browser if custom tabs aren't supported. So it's now in-app.

**Comment by charlag** [comment]
@galopeian1 @alerque are you still affected by this?

**Comment by charlag** [comment]
I will close this issue, I think it works now, feel free to reopen
