### ISSUE TITLE
Not able to copy text from any post

### ISSUE THREAD

**Issue by yookoala** [Vavassor/Tusky#147]
This is a minor usability issue.

By long pressing the status's text, user would hope to pop the "Copy Text" pop-out and copy some of the text. It is not possible now. Long press simply have no effect.

**Comment by alerque** [comment]
Huh. You jinxed me! I actually searched for this issue yesterday, but then didn't get around to filling out a report until just now. I'll close mine as a duplicate, but since I went into a bit more detail on how this could be fixes I'll add it below.

----

With all the languages floating around the fediverse I frequently find myself wanting to translate toots. My French just isn't that good. Right now the procedure to do that is to share the toot to something from which I can rip out the URL (#148 would help with this, I don't have a share-to-clipboard), then paste the URL in a browser, then select the text and copy it, lastly pasting it into a translator.

Many programs make this a lot easier. Three things should make this a lot easier:

1. Make the text of toots selectable. This would make portions of toots easier to grab.

2. Add "copy toot text" as well as "copy toot link" to menu on each toot.

3. Add a share text item to toot menu in addition to the share link option.

Any of these would help, but all of them would add a lot of flexibility.

**Comment by charlag** [comment]
Is this still relevant? We have an option to copy text now.

**Comment by charlag** [comment]
You can copy through the "share" menu.

**Comment by MasterGroosha** [comment]
@charlag However you cannot select a piece of text, only all or nothing.
