### ISSUE TITLE
Display loader state when upload a media

### ISSUE THREAD

**Issue by ucodi** [Vavassor/Tusky#195]
Display a loader bar for watching thet state of upload

**Comment by wxl** [comment]
To confirm, this would show the progress between attaching media and the appropriate URI being added to the toot? 

Because there's a "finishing media upload" state that I sometimes get stuck on. I can see a spinner but no clear indication it will ever end. This could use an actual progress meter and that's what I'd suggest for the bug above.

**Comment by charlag** [comment]
This should be closed by #426
