### ISSUE TITLE
Duplicated interface

### ISSUE THREAD

**Issue by Dariasteam** [Vavassor/Tusky#20]
I don't know how to reproduce it yet, but it happened two times after swipe down to update. Its like if the background of the app were a screenshot taken at the moment of the update. My device is a Motorola Moto G2 (2014). Sorry for my grammar mistakes.
![screenshot_20170308-174810](https://cloud.githubusercontent.com/assets/9285997/23861121/f4bac31e-0800-11e7-8588-3bd86393138b.png)
![screenshot_20170308-174815](https://cloud.githubusercontent.com/assets/9285997/23861124/f8633b9a-0800-11e7-87ec-3c6d40704203.png)
![screenshot_20170308-174807](https://cloud.githubusercontent.com/assets/9285997/23861127/fc5d1d10-0800-11e7-99a8-d6d7d5f03027.png)

**Comment by alerque** [comment]
I saw the federated timeline do this once. Scrolling moved one set of widgets while another fixed set were drawn on top.

**Comment by Vavassor** [comment]
I've seen a lot of folks informally post pictures of this on public timelines. I've "fixed" it before but I've never closed this issue because it never goes away entirely. It seems to equally affect thread views and timelines.

It's always related to RecyclerView being de-synced with the data set in its adapter.

**Comment by daycode** [comment]
it happen to me today because I had a low flow

**Comment by Vavassor** [comment]
This was closed by pull request #360!
