### ISSUE TITLE
"The redirect uri included is not valid." when trying to authorise with mastodon.social

### ISSUE THREAD

**Issue by Fiona** [Vavassor/Tusky#203]
I'm not entirely sure that this is Tusky's problem or mastodon.social's problem.

I was using Tusky happily for some time now, but I logged out to try another instance. I wanted to log back into mastodon.social and now when I try to authorise it opens a page on mastodon.social in my mobile browser that simply says "The redirect uri included is not valid."

Here's the URL that it sends me to (With the client ID removed, I don't know if it's something that shouldn't be public.)

https://mastodon.social/oauth/authorize?scope=read%20write%20follow&response_type=code&redirect_uri=oauth2redirect%3A%2F%2Fcom.keylesspalace.tusky%2F&client_id=<client id>

Tusky is rendered completely unusable with this error, I can't seem to fix it. :(

**Comment by alerque** [comment]
Were you able to log into some other instance?

Does the authorization open up in an external browser or a Chrome Tab for you?

**Comment by Fiona** [comment]
Hm it seems to be specific to mastodon.social. I just tried an account on social.wxcafe.net and Tusky is okay with that. The main mastodon.social is still not working. Should I close this and post an issue on the mastodon project? I mean it _could_ still be something Tusky is doing.

It opens up in an external browser, in this case Firefox Mobile.

**Comment by daycode** [comment]
I've just try and it works for me on mastodon.social 🤔 in emulator and in my phone less chrome, perhaps an issue with firefox mobile ?

**Comment by Fiona** [comment]
I just cleared Firefox's defaults and tried Chrome and it's occurring there too. Well that's good, it removes that possibility.

**Comment by daycode** [comment]
and with the default android browser ? can you send me your android version 😉

**Comment by Fiona** [comment]
I'm not sure what you mean, I don't have a default android browser, Chrome is the default on this phone. It's Android 6.0.1.

**Comment by Vavassor** [comment]
@Fiona I'm pretty sure this is my error. Clearing app data or reinstalling should fix it.

Long-winded explanation:

The redirect URI is something I get to define arbitrarily, basically just to tell android "if you get a link that looks like this, send them to my app because it's not a website". There was an error where I was giving instances was supposed to be ```oauth2redirect://com.keylesspalace.tusky``` but I had accidentally built it in the wrong order so it was ```com.keylesspalace.tusky://oauth2redirect```. This past update I switched it back to the way I originally intended.

You specify it during app registration and it partially uses this to calculate the client ID/secret. And then later when you authorize to login you specify the redirect URI again and it checks that the id/secret pair match the redirect URI just as a secondary measure to make sure the app is who it's saying it is.

The client ID and client secret are saved by Tusky the first time you log into an instance and just loaded from SharedPreferences every time afterward. So the problem is, the new code is specifying the new redirect URI for authorization but then it loads the client ID and secret that are built with the OLD redirect URI.

In order to (try to) prevent this from occurring to anyone else I made a short piece of code in LoginActivity that was supposed to run the first time this version is run that would just clear out the now-invalid client ID's and secrets. But, it seemingly hasn't run for some people and they just get this mysterious "redirect uri not valid". I've had like 4 other folks also report this. So, I must've made some mistake in this one-time piece of code.

**Comment by Fiona** [comment]
Hi! Clearing the app data did indeed do it. :) Thank you very much.
Also thank you for the big explanation! I'll leave this ticket in your hands as a reference for you. 
Thanks again!
