### ISSUE TITLE
Access to the "Follow requests" panel.

### ISSUE THREAD

**Issue by frodon1** [Vavassor/Tusky#222]
For a private account, any follow request must be approved. In the web interface of mastondon this is done in the "Follow requests" panel.
Is it possible to a "Follow requests" panel in Tusky to accept or refuse the requests ?

**Comment by Vavassor** [comment]
Aye, this was something I was thinking of for the next update since I was already doing some catch-up with mastodon site features (muted users list, direct messages, etc.).

Also, when you follow a locked account it doesn't make it clear that you've just submitted a request and that it has to be accepted, it just acts that same as a follow. So, the interactions with locked accounts are kinda weak, right now.

**Comment by wxl** [comment]
Um this is closed which suggests fixed, but I'm not necessarily seeing this changed. Perhaps it hasn't been released yet?

**Comment by Vavassor** [comment]
Yes, I closed the issue with the commit that added it, but the release is coming tomorrow.
