### ISSUE TITLE
resize image of a post

### ISSUE THREAD

**Issue by ucodi** [Vavassor/Tusky#223]
Resize image of a post which is more than 4 Mo to add it.

**Comment by Vavassor** [comment]
This already happens? The camera in my phone actually generates most images larger than 4MB by default, so I ran into the problem very early. Right now, it scales down to the nearest convenient size that fits the larger side within 1024 pixels.

This is pretty arbitrary. I originally picked 4096 because a 4096 pixel square .jpg is frequently near/under 4MB (more like 3.2-3.7, from what I tested). But I realised that was quite a bit larger than most monitor or phone screen sizes. So all it really did was inflate upload times and take up more server space.

**Comment by daycode** [comment]
it does, my mistake, but apparently it's the ratio height / width which is more than 1280 x 1280 which cause problems on upload (a user scaled down his image and it works for him) and I found that too

https://github.com/tootsuite/mastodon/issues/2252
