### ISSUE TITLE
[App Crash] When selecting favourites from menu (latest commit 7d83a9a)

### ISSUE THREAD

**Issue by PhotonQyv** [Vavassor/Tusky#245]
Having cloned the latest source of Tusky I've noticed that the app crashes if you choose 'Favourites' from the menu, I don't know enough about the code to be able to work out why it happens, but I know it happens in FavouritesActivity.java, at line 44, fragmentTransaction.commit().

**Comment by Vavassor** [comment]
Oh, this was a silly omission. FavouritesActivity is supposed to implement the interface SFragment.OnUserRemovedListener as of 5179d7e9b32ec191268147df3c66ee02b814457b and I just forgot it. So it was giving a ClassCastException.

Basically in order to remove users's posts when they are blocked or muted, a timelined fragment is supposed to tell its parent activity through this interface. Then, it keeps references to all its currently-loaded fragments that have timelines and notifies each of them to remove the posts by that user.

Sidenote: in FavouritesActivity this is actually a pretty silly interaction because there's only one fragment and one activity. The fragment tells its parent who just tells it right back to remove the posts.
