### ISSUE TITLE
Image attachment upload crashes app

### ISSUE THREAD

**Issue by wxl** [Vavassor/Tusky#247]
It doesn't happen with every image, but using [this one][1] it happens repeatably. It also happens with multiple images. I can never get past one image. No error, no success, no progress meter. Just a crash. 

[1]: https://pictor.ialis.me/media_attachments/files/000/035/774/original/aab22f881c0e22a2.jpg

**Comment by daycode** [comment]
Few French people had that too, solved with resize image less than 12080x1280 😉 
see https://github.com/tootsuite/mastodon/issues/2252

**Comment by wxl** [comment]
Well, the way the web client deals with it appears to be that it resizes first. I think Tusky should do that as well. It's kind of a pain to deal with resizing images on mobile. That that it's not doable, but still problematic.

Does that also solve the multiple image issue?

**Comment by Vavassor** [comment]
This is definitely not a server issue. It should give an "upload failed" message if that's all that it was, never crash.

Unrelated to the crash, but:
Right now Tusky resizes images but only if they're larger than 4MB, which now I'm thinking is really a pretty bad strategy. 3G network maximum upload speed is only 0.2125 MBps so it'd take 18 seconds to upload one image at BEST. So, that's bad. It'd probably be better to just resize any images larger than a limit to guarantee fast uploads.

**Comment by d3vgru** [comment]
I was able to get OP image to post using a recent build from master but I can't currently get a link to the post because the share button doesn't do anything

**Comment by Vavassor** [comment]
This turned out to be something I just straight up wrote wrong. Some phones, when you flip or rotate the photo, instead of changing and re-saving the pixel data in the file, they just change a piece of EXIF metadata that tells the orientation. So, when I'm making a resized copy I also have to read if this info is there, and turn it the right way around. If it needs reorienting, it makes a copy and hits this error, so any image that's been turned or flipped after taken would crash this.

The actual crash is caused because ```Bitmap.createBitmap``` does not necessarily make a copy, it can apparently just hand you back a Bitmap with a few variables changed that references the source image. So if you call ```recycle()``` on the source image that was done this way, it also invalidates the new image. And then, accessing the invalidated image causes an ```IllegalStateException``` and crashes.
