### ISSUE TITLE
Do not crop image thumbnails 

### ISSUE THREAD

**Issue by snaggen** [Vavassor/Tusky#250]
Images thumbnails in posts are currently cropped to a wide aspect ratio. This basically destroys the image, when you take a photograph composition and framing is important. Show the whole image or not at all. You wouldn't take a text post and loop that through google translate multiple times and distort it.....

**Comment by daycode** [comment]
can you send an example ? 🤔

**Comment by snaggen** [comment]
https://mastodon.social/users/WelshPixie/updates/2198888

**Comment by snaggen** [comment]
If you look at that post in Tusky, the thumbnail is cropped wide compared to the real image you get when clicking on it. I don't know how it looks in the web gui, since I have not used that.

**Comment by snaggen** [comment]
Ok, clicking on this link on Android opens the web with an even worse crop....

**Comment by Vavassor** [comment]
This is a bit rambly, but here's concerns with different possibilities.

Not cropping with one image is mostly fine, but it becomes a problem in cases like where you have a tall portrait orientation image but your device is turned landscape. So you get a huge tall image that fills up the timeline and you can't even see it on the screen at once. You could limit how much space it fills by setting a maximum scale size to prevent this. But it can be kind of ugly with some image shapes because of how much negative space it leaves to the sides.

With multiple images, you need them to all be the same aspect ratio to have a photoset layout. Putting the images all one after another is an option, but you will end up with very long posts. And in a photoset the only options are cropping or letterboxing. Letterboxing could work, but if you pair wide and tall images in the same set it'll end up with images that are mostly margin and so small you can't tell what they are.

Also, another possibility is to shorten long posts and have an "expand" button. But for photosets this is a weird choice, because you started with a cropped image where you can't see the whole pictures and now you have a shortened post where you can't see ANY images.

**Comment by snaggen** [comment]
I agree that there will be aspect ratios that will be suboptimal. But that
is already the case, just that now the portrait case currently shows the
lower part of the face and the upper part of the chest instead of pillar
boxing.
I suggest to define a max height, the same as the current width an then
scale to that using original aspect ratio, pillar box if needed.

Den mån 1 maj 2017 00:17Vavassor <notifications@github.com> skrev:

**Comment by snaggen** [comment]
In general I would look at how this is handled in Google+, they worked close with the photo community to get thing to look good both to photographers and regular users.

**Comment by connyduck** [comment]
This should be fixed, since 1.4 images in timelines have a better aspect ratio.
