### ISSUE TITLE
F-Droid build still requires firebase (is most likely a leftover)

### ISSUE THREAD

**Issue by krt16s** [Vavassor/Tusky#274]
In `app/src/main/java/com/keylesspalace/tusky/BaseActivity.java` `com.google.firebase.iid.FirebaseInstanceId.getInstance().getToken()` is called and should either be moved or repalced by a dummy for the fdroid build.

**Comment by Vavassor** [comment]
In the FDroid build ```BuildConfig.USES_PUSH_NOTIFICATIONS``` is false, so the branch with that Firebase call shouldn't be included in the build. But it would be cleaner and clearer to move it for sure.

**Comment by Vavassor** [comment]
I started to separate out the notifications into an object which kept track of the ```TuskyAPI``` and ```PendingIntent``` but it ended up causing an odd crash. I think it was due to it keeping references to something it wasn't supposed to outside the activity lifecycle?

Anyhow, it ended up being trouble so I reset and just did it the "single method with a dummy counterpart" way.
