### ISSUE TITLE
Where to report bugs?

### ISSUE THREAD

**Issue by KonomiKitten** [Vavassor/Tusky#3]
Should bugs be reported to GitHub, Playstore or both?

**Comment by Vavassor** [comment]
If it's a crash or freeze it's REALLY helpful to get a report through the play store. Because it sends me not just the comment/report but also in the background it sends a log and stack trace which really helps to narrow down the point of failure.

But, for other bugs I'd appreciate them reported here if possible. Not all users are getting the app through google play, for one. Also, having room for more description and back-and-forth is nice. I know it's also possible to keep a record of what commits & versions close a particular issue, so I'd like to leverage that going forward.

But of course, I know not everybody knows how to or wants to use github so I'm going to check both places anyway.

**Comment by KonomiKitten** [comment]
Okay I used Playstore to send my crash log, closing this issue, thank you for the reply.
