### ISSUE TITLE
Privacy statut of answer shoould be the same the original toot

### ISSUE THREAD

**Issue by GuyM-31** [Vavassor/Tusky#303]
If in the last toot, you set privacy to "direct" next toot will "direct" even if you answer to a "public" toot.
The privacy statut of an answer to a toot should be same of toot you answer to.

Si vous avez pouété "direct" le pouet suivant sera "direct" même si vous répondez à un pouet "public".
Le statut de confidentialité d'une réponse devrait être identique à celui du pouet auquel elle répond.

**Comment by Vavassor** [comment]
It should always inherit the visibility of the toot you're replying to. But for public visibility, there was an issue fixed in commit 1dc9c87c2e372e67aa476fa28c4d4596bd94f7fc that disabled public as an option for replies. So, in your example, it would try to set to "public", fail, and keep the "direct" visibility.
