### ISSUE TITLE
requesting status update

### ISSUE THREAD

**Issue by borysn** [Vavassor/Tusky#311]
hi,

my name is borys. i wants to start contributing actively. i'm falling in love with mastodon. tusky app is best so far. it's good. but it has a few issues.

i'd like to start contribution by going for multiple account setup, and then start tackling some usability issues. 

i'm just not sure what the status of development is. what are the issues being taken care of already. what's not being taken care of. is there anything seriously holding up development? etc.

thanks!
BHN

**Comment by borysn** [comment]
in short, i'd like to use this thread to come up with some sort of ad hoc agile model in my head. unless it already exists!

**Comment by Vavassor** [comment]
For the next Tusky update my plan was getting push notifications working again. They've been entirely broken for a long time (See #84). I'd also wanted to remove Firebase. Even though it's nice, it restricted being on F-Droid's store because it uses a proprietary library and service. Also, it required adding special clauses in the GPL license to allow it.

The prototype server replacement that I've been introducing as of Tusky-1.1.4-beta has been promising! But it's slow development because server-side work is new to me (I'm not good at it). Also I've been gone on a trip with family this past week.

**Comment by Vavassor** [comment]
Anyway, that's the main thing in-progress that I'm working on.

I've been unemployed since the project started (January?). Frankly, that's made it harder to justify spending more time with it. That's been why my development has slowed more than any technical reason.

**Comment by borysn** [comment]
@Vavassor thanks for the update. i did hear a lot of people want the notifications. and i understand where you're coming from with work. i'm in a similar boat, but i'd like to dive into something head on atm. and i've been using tusky a lot. so this is a green light for me.

i'll check out the notification issue, it'll be a good start to dive into the code base and all. i don't have anything going on for the weekend anyway. 

i'm gonna close out this issue for now.
