### ISSUE TITLE
[Discussion] Notification tab actions

### ISSUE THREAD

**Issue by charlag** [Vavassor/Tusky#322]
Currently, when you tap on notification in Notifications tab it opens the person notification is related to but there's no way to open the toot which notification is about.
I propose to change current behavior for fav/boost notifications and open the toot of the notification by tapping content of the notification while account would be opened by tapping the line on top of the toot (like XX favourited your toot/XX boosted your toot). Behavior for replies/follow notifications should stay the same.
I already implemented boost handling in #321 and changing behavior would be really easy and I am eager to implement it. Please, post your thought and opinions.

**Comment by averageunicorn** [comment]
Yes, this. There were a few times when I was happy about this behaviour, but usually it's not what I want or expect.

One concern though: Hitting exactly the "XX favourited your toot" line can be a bit difficult. I'm a bit clumsy, and I already miss roughly-one-line-high things like readmores more often than not.

A solution might be: Tapping the text area (including the "favourited your toot" line, because short replies would still be hard otherwise) opens the toot, and tapping the blank area left of the text opens the profile.

…but I'm happy with any solution that leaves some room for clumsy people.
