### ISSUE TITLE
Timeline optimization proposal

### ISSUE THREAD

**Issue by charlag** [Vavassor/Tusky#323]
There are few things which I find inefficient in the current implementation of timeline.
First, R.layout.item_status contains 4 RealtiveLayout's. We can get rid of some of them (like status_reblogged_bar can be LinearLayout or FrameLayout) and we can implement what's left using ConstraintLayout (which is far more efficient). Using ContraintLayout we can flatten hierarchy a lot and get rid of some extra views (like Space).

My second concern is about StatusViewHolder. While binding to the Status it creates new View.OnClickListener objects for many views. We would like to avoid allocation of object during binding because it creates many small object fast.
There are multiple levels of optimization which we can choose from.
The most clean one is creating View.OnClickListener's during creation of the holder. While binding we store passed listener. When action happens View.OnClickListener triggers StatusActionListener.
Another option is less clean but more efficient. We can set ourselves as Listener and differentiate views by their IDs.

I, myself, would go with the first option. I am eager to implement any of these listed changes (they should be separate PRs).

**Comment by Vavassor** [comment]
I'd appreciate any of this you might want to do. I was planning for 1.1.5 (version after next) to add correct right-to-left support and was possibly going to simplify the layouts a bit, then, but you're welcome to sooner if you want.

Usually when I use RelativeLayout needlessly, like in the status_reblogged_bar, it's because I was looking for a way to center something before I learned about gravity/layout_gravity.

Moving the View.OnClickListener's to the holder's constructor sounds easy enough, just something I never thought to do. The view ID way sounds like it could be janky, so I'd be wary of it.

**Comment by charlag** [comment]
I think it's safe to close it then? I may work on it when I'll have time.
