### ISSUE TITLE
adding photos (almost) always fail

### ISSUE THREAD

**Issue by govvin** [Vavassor/Tusky#345]
I am unable to add photos to my toots. Undetermined error.

**Comment by connyduck** [comment]
Could you please provide additional information, like what phone you use and on what Tusky and android versions you are on?

**Comment by govvin** [comment]
@connyduck This happened using Tusky v1.1.3 on a Note 3 running Android 5.0.

**Comment by govvin** [comment]
Seems to be related to image size? Images ~300kb is getting through without issues.

**Comment by connyduck** [comment]
Oh this was the crucial information I looked for. I can now reproduce the error. Will keep you postet if I find any solutions.

**Comment by connyduck** [comment]
I was not able to post large images because I got a timeout exception most of the time. So I increased the timeout, now everything works fine.
https://github.com/Vavassor/Tusky/commit/5fff9e2bdcf96241eb173f6d19167f33910e1c04

Please test the next Tusky release for this issue and report if this fixed it for you.

**Comment by govvin** [comment]
I will @connyduck . When is the next release, btw?

**Comment by connyduck** [comment]
Tomorrow!

**Comment by govvin** [comment]
Hello. This issue has been fixed in the latest release. Thanks!
