### ISSUE TITLE
Follow/Unfollow button in corner - dear gods, why?

### ISSUE THREAD

**Issue by TrollDecker** [Vavassor/Tusky#359]
[Screenshot](https://social.diskseven.com/system/media_attachments/files/000/045/680/original/f277e02e82282281.png?1501061311)

I'm not going to sugar-coat this: sticking a floating follow/unfollow button in the bottom right corner of user profiles, especially one without *any* kind of confirmation, is a terrible idea, just asking for disaster. It's in a good position for users on their phones to accidentally touch the button with their hand and follow or unfollow a user without intent or realisation, and before anyone jumps in and says that you can easily reverse it, maybe there's a good reason to never have to do so in the first place.

It's also against [these guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button) if anyone considers at least unfollowing a user to be a destructive action. I know I do.

If you must have a floating button there, why not something more logical like "Mention User"? That would make more sense.

**Comment by connyduck** [comment]
Because it was easy to implement I guess.
But I agree with you, this should be changed.
If it is ok with @Vavassor I can implement this in the next week or so.

**Comment by Vavassor** [comment]
Actually yeah, this is pretty fair. Especially in the case of accidentally unfollowing someone without noticing. I guess I'd find space for it in the header and add a button to the toolbar when it's collapsed? Just adding a confirmation dialog to the existing button would possibly be sufficient, but it's a little odd thinking of the button as a quick action and then having it ask permission.

By the way, it started out as just a follow button, but some folks were confused at how to unfollow because they didn't know the action was also in the tricolon ⁝ menu. So it seemed best to just add that to the same button and flip the button depending on if you're already following or not.

**Comment by TrollDecker** [comment]
A follow button could probably just sit on the profile header, to be honest. There's more than enough room there. I think. 🙂

**Comment by charlag** [comment]
I liked how it worked as @Vavassor described, but yeah, it probably was confusing.
With current design I accidentally unfollowed few people (multiple times Gargron) so I am for the change.

**Comment by Vavassor** [comment]
I added a warning dialog when unfollowing to that pull request with commit 973c6168f84e09d7c1ae27eb4c3a968c0a49b6cb.

So, the follow/unfollow button is moved to the header and the floating action button is now a mention button.
