### ISSUE TITLE
Please support Google Gboard gif input 

### ISSUE THREAD

**Issue by trashhalo** [Vavassor/Tusky#402]
![screenshot_20171021-105039](https://user-images.githubusercontent.com/177491/31852912-0e9aed08-b64e-11e7-81ba-51697ae6cd0d.png)

**Comment by trashhalo** [comment]
https://developer.android.com/guide/topics/text/image-keyboard.html

**Comment by Vavassor** [comment]
I put this in a long time ago, but the issue was it never was able to upload reliably and would just error out. I think this is more generally due to how unreliable the media uploads were, but exacerbated by the fact that GIFs and .webp tend to be much larger.

Anyway, I deactivated it by commenting this bit out https://github.com/Vavassor/Tusky/blob/f2f3be37b3be75e105fc03fe143b165c44fa56e2/app/src/main/java/com/keylesspalace/tusky/ComposeActivity.java#L341 so it'd be easy to turn back on, but would still have difficulty uploading.

**Comment by connyduck** [comment]
Oh that would be a really nice feature, I will look into this.

**Comment by connyduck** [comment]
https://github.com/Vavassor/Tusky/commit/2dfd83ef978a627a342974a16b1f9dfcceb13668 ✅
