### ISSUE TITLE
When writing a reply, text disappears if app switches from portait to landscape

### ISSUE THREAD

**Issue by xuv** [Vavassor/Tusky#45]
Tusky v 1.0.3
Steps to reproduce:
 - Click reply to a toot and start writing after the usernames
 - Rotate the phone from portrait to landscape

Result:
 - The text entered disappeared. Username still there.

Expected result:
 - The reply content should be the same before the phone rotation.

**Comment by Aldarone** [comment]
I'm on Tusky 1.1.0 and the app crash when I do this.

**Comment by raphaelbastide** [comment]
I confirm bug exists on my Android phone.

**Comment by alerque** [comment]
I've seen something similar but maybe not the same bug while switching between apps. A toot I was writing has gone missing several times but I haven't been able to pin down the circumstances. Given that my device is orientation locked it is some other app redraw event.

**Comment by Vavassor** [comment]
I know the crash that @Aldarone has is already fixed, so that will be fixed in 1.1.1.

The EditText (the main text box for the compose page) is actually recreated every time the activity is created. But the text and selection state is saved in a Bundle called savedInstanceState and restored manually to the newly-created EditText. So, either the saving or restoring side of that process isn't happening in some case.

**Comment by xuv** [comment]
@Vavassor If that helps, the text restoration is happening as expected when calling a new toot. It's just when responding that it bugs.

**Comment by Vavassor** [comment]
The compose page is not longer recreated when reorienting so there's no way for this bug to occur now.
