### ISSUE TITLE
Missing expected Android UI elements

### ISSUE THREAD

**Issue by alerque** [Vavassor/Tusky#64]
There are a few basic UI elements one expects to find that are missing.

Most notably headers for the preferences panes need to be added that tell what screen you're even looking at and have back buttons. Individual toot screens have this as expected but the preference screens don't.

When scrolling way down in a timeline there doesn't seem to be an easy way back to the top. One is forced to flick enough to scroll all the way back.

An "About" entry in the main nav with links to the project page and where to file issues would also be nice.

**Comment by Vavassor** [comment]
I hadn't given the preferences thing much thought, since it only recently expanded to a second screen. But, especially as more preferences are added, the app bar would be good.

You should just be able to tap the tab for the timeline you're currently on to jump to the top. But with things like the favourites timeline and block list, that don't have tabs, there's no way to jump upward yet.

And yeah, an about page is nice although talking with translators has made me wary of adding unnecessary text, haha

**Comment by alerque** [comment]
Should I split this up into separate issues for tracking? I was writing this from mobile and got lazy.

Yes I agree on keeping the strings to a minimum, but a very basic one that shows the version number and links to keep places like the issue tracker shouldn't need more than a couple words.

**Comment by sbetelmal** [comment]
I am happy to add a simple about page that shows the version number.

**Comment by connyduck** [comment]
I added ActionBar to Preferences https://github.com/Vavassor/Tusky/commit/93fcd33c48b34a1d84c17122c756845873cea9ea

**Comment by charlag** [comment]
@connyduck as you've added Toolbar to Preferences, there's a link for bugs in About and one can scroll up by clicking on the tab icon on the top I think this can be closed now?
