### ISSUE TITLE
GPLv3 violation

### ISSUE THREAD

**Issue by grawlinson** [Vavassor/Tusky#86]
@FlorentAnders is trying to pass off your work as an independent application.

* [Reddit post](https://www.reddit.com/r/androidapps/comments/63w8fc/dev_a_polished_beautiful_and_wellworking_mastodon/) by the 'author'.

* [Google Play](http://play.google.com/store/apps/details?id=com.fa.sera) link of the 'app'.

* [Open issue](https://github.com/tootsuite/mastodon/issues/1105) upstream (Mastodon).

**Comment by alerque** [comment]
It looks like the best thing to do here is for @Vavassor file [a report here](https://support.google.com/legal/contact/lr_dmca?&product=googleplay) naming the GPL infringement and explaining the rip off situation. I haven't reviewed the TOS lately but this seems like this is a kind of sleaziness they'd be interested in shutting down entirely.

**Comment by SkyzohKey** [comment]
Also sent à takedown.

**Comment by Vavassor** [comment]
Technically, Tusky is LGPL right now. I was under the impression that because I was linking with and redistributing Firebase's proprietary libraries, that that would've been a GPL violation itself, so I changed at that time. What I should've done is kept it as GPL and provided an exception for Firebase, which I've learned is possible [here](https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs).

At any rate, they still aren't providing source or including the license and attribution.

**Comment by grawlinson** [comment]
Also the [Sera](https://github.com/FlorentAnders/Sera) repository was created Feb 7 2016, so the intent to violate the license has been there for a while.

**Comment by Vavassor** [comment]
@grawlinson From their website, it looks like Sera was originally the name of a photo app of some kind? So the github might've been for that. http://madebyfa.de/sera/

**Comment by mariotaku** [comment]
Feels soooooooooo ironic when I read their [ToS](https://web.archive.org/web/20170407111240/http://madebyfa.de/terms-of-use/)

**Comment by FlorentAnders** [comment]
I just removed the app from the Play Store. Please excuse what I did, I was not aware of the fact that I needed to publish the source code.

**Comment by mitchellurgero** [comment]
@FlorentAnders - Although I understand the mistake, others might not (I am not a dev for this project - but I am 100% supportive to the author as a used-to-be Mastodon instance admin)

Before forking a project, always always always read the LICENSE file that came with it. ALWAYS. Some projects on GitHub, GitGud, etc do not use the GPL license as an example it might be MIT license.

Just remember to read the license next time.

**Comment by FlorentAnders** [comment]
@mitchellurgero I will definitely now. As I already wrote in another issue, I have absolutely removed access and ad serving to both apps, I really understand what I did was wrong. The only problem I currently have is that because of the fact that these apps get removed, my account with my two other apps could be closed.

**Comment by mitchellurgero** [comment]
@FlorentAnders If you are talking about Google Play - I believe you can appeal that case - if you took the apps down yourself then there is no worry.

**Comment by FlorentAnders** [comment]
@mitchellurgero Yes, I am talking about Google Play. Thank you.

**Comment by SkyzohKey** [comment]
Woops, might be my fault as I sent a takedown request to Google. Sorry for that but as a software developer, especially one loving and preaching FOSS, I was in the obligation to report that. Seeing the same app with just ads added made me think «this guy is stealing work in order to make profit, it needs to be deleted.»

**Comment by FlorentAnders** [comment]
@SkyzohKey To be honest, I feel like saying it was exactly the same app was a little bit too much. The navigation drawer was completely reworked, the content design looked much better, translations were updated and optimized and there were other design changes combined with a little bit of more customization. But everyone needs to know where an app is a "copy with ads" and where it is not. I have still agreed to unpublish the app, but to be honest, talking before doing might have been nice. And if I should lose my Google Play account because of all of this, trying to help me to get it back (what won't me make publish those apps again) would be nice too.

**Comment by alerque** [comment]
@FlorentAnders Dude why are you trying to defend this again. You said you understood why it was wrong, now you're back-peddling. You took several other people's hard work which they offered up for free to other users on an open source platform where it's obvious that the modus operendi is to help build better things together, you stripped off all the branding and any mention of it being somebody else's project, then you stuck ads in it and posted it as your own. It doesn't matter if you fixed some things up and changed some stuff around, that's a sleezy thing to do.

To make matters worse you happened to thing to a project related to the Mastodon network which has just gotten off the ground thanks to lots of generous people sharing their coding time and server resources. Everybody is exceptionally generous right now with lots of servers and coders riding a wave of donations. Right the middle of that you tried to steal their work, make it look like all your own, then profit off of advertising?

If you really know what you did was wrong, how about contributing your improved code back to the community? If it's really better let others benefit from it. And if it's really worth something, maybe then look for sponsorship for your work. But to be honest it didn't look to me like you'd actually improved it much, just kicked the tires a little.

It's actually perfectly legal to take an OSS project and make some changes to it and republish it. It's generally known as forking and if people like your version better that's great. But most OSS licenses require you publish the code for any changes you make and/or credit the original project and/or not sell it for profit. Which combination of those rules varies by license but even if you hadn't read the specifics of this project common sense should have warned you rebranding something to strip out the source of most of the code and adding advertisements to something that was posted by it's original authors for free without ads was not a good-faith move. So stop trying to excuse it.

**Comment by FlorentAnders** [comment]
@alerque Yes, you are right, what I did was wrong and I do not say anything that isn't this.

**Comment by FlorentAnders** [comment]
Hello, I am currently planning to re-release my own variation of a Mastodon client, probably based on Tusky again, only with interstitials. I will definitely release the source code this time, I learned from my error.

Greetings!

**Comment by FlorentAnders** [comment]
Hello,

I have re-published a new, more to my taste and GPLv3 compliant Tusky-based Mastodon client.

https://github.com/FlorentAnders/Panoramic

**Comment by alerque** [comment]
@FlorentAnders Many of the new files in your fork are littered with copyright notices that are incompatible with extending a GPL project:

    

If you are going to fork and extend a GPL based project you are required to release your modifications under the terms of the GPL as well. This is the basic premise of copy-left licensing. In other words you may not stipulate extra terms like retaining copyright or demanding people request your permission. By necessity, any code you write and include in the repository that modifies or extents the base program will be legally bound to the GPL, not to any notice like the above.

Additionally, threatening DCMA takedowns is more than a little bit pretentious given your own history of license violations and the fact that you aren't the primary upstream source for this code.

>  Copying the app and not releasing your source code will follow in a Digital Millenium Copyrights Act request that will result in a takedown of your app. I am serious about this.

For the sake of your own reputation in OSS circles I suggest you just drop that line. At most end the previous sentence with "…provided you also release the source code under the terms of the GPL." Respect has to be earned, not demanded.
